### ISSUE TITLE
Cannot reproduce the testing result in the paper

### ISSUE THREAD

**Issue by thomasly** [duolinwang/MusiteDeep#10]
Hi Dr. Wang,

I was trying to reproduce the result in your paper with the trained model weights in this repo. To construct the benchmark dataset, I followed your method in the NAR publication (Wang, D. et al., Nucleic Acids Research 48, W140–W146, 2020) by using the modified sites of proteins released after 2010 as positive data and the rest sites in the same protein as negative data. However, the model performance was not as good as your publication. Especially in the o-glycosylation, ubiquitination task, and phosphoserine/threonine tasks. Could you give out more details about how you constructed the independent benchmark and how to produce the results in Table 1? Thank you so much!

Best,
Thomas

**Comment by duolinwang** [comment]
Hello this repository is an old version and only provide prediction for phosphorylation sites not for other PTMs. 
You should refer to https://github.com/duolinwang/MusiteDeep_web/tree/master to reproduce the results in the NAR paper or just try our webserver https://www.musite.net/.
